import { CheckCircle2, LineChart } from "lucide-react";

const benefits = ["Automated Financial Reporting", "SSO Student Verification Integration", "Departmental Budget Allocation"];

export function ForUniversities() {
  return <section id="universities" className="overflow-hidden bg-[#f7f7f5] py-8 sm:py-24"><div className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-8 px-6 lg:grid-cols-2 lg:gap-16"><div><h2 className="text-[28px] font-bold leading-[34px] tracking-[-0.02em] text-zinc-950 sm:text-4xl sm:leading-11"><span className="sm:hidden">For Universities</span><span className="hidden sm:inline">Designed for Administrative Clarity</span></h2><p className="mt-4 text-base font-medium leading-6 text-zinc-500 sm:mt-6 sm:text-xl sm:leading-[30px]"><span className="sm:hidden">Reduce administrative overhead, eliminate cash handling risks, and gain unprecedented insight into campus economic health with our turn-key blockchain solution.</span><span className="hidden sm:inline">Deploy a private or public payment ecosystem in minutes. CampusChain provides university admins with real-time financial oversight, automated scholarship distribution, and secure identity management.</span></p><ul className="mt-8 hidden space-y-4 sm:block">{benefits.map((benefit) => <li key={benefit} className="flex items-center gap-3 text-base font-medium"><CheckCircle2 size={20} />{benefit}</li>)}</ul></div><DesktopMockup /><MobileMockup /></div></section>;
}

function DesktopMockup() { return <div className="relative hidden lg:block"><div className="relative z-10 mx-auto max-w-md rotate-2 rounded-2xl border border-zinc-200 bg-white p-8 shadow-xl"><div className="mb-8 flex items-center justify-between"><div className="h-4 w-24 rounded bg-zinc-200" /><div className="size-8 rounded-full bg-zinc-200" /></div><div className="space-y-6"><div className="flex gap-4"><div className="h-20 w-1/3 rounded-lg border border-zinc-200 bg-zinc-100" /><div className="h-20 w-2/3 rounded-lg bg-zinc-100" /></div><div className="h-4 w-full rounded bg-zinc-200" /><div className="h-4 w-5/6 rounded bg-zinc-200" /><div className="h-4 w-4/6 rounded bg-zinc-200" /><div className="flex justify-between border-t border-zinc-200 pt-6"><div className="h-8 w-16 rounded bg-zinc-950" /><div className="h-8 w-16 rounded bg-zinc-200" /></div></div></div><div className="absolute -right-10 -top-10 size-64 rounded-full border border-zinc-300 opacity-20" /><div className="absolute -bottom-10 -left-10 size-48 rounded-full bg-zinc-200 blur-3xl" /></div>; }
function MobileMockup() { return <div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl bg-zinc-950 p-6 shadow-2xl lg:hidden"><div className="flex items-start justify-between"><div className="h-2 w-12 rounded-full bg-white/20" /><div className="flex gap-2"><div className="size-3 rounded-full bg-white/40" /><div className="size-3 rounded-full bg-white/40" /></div></div><div className="mt-14 space-y-4"><div className="h-8 w-2/3 rounded bg-white/10" /><div className="grid grid-cols-3 gap-2"><div className="h-16 rounded bg-white/5" /><div className="h-16 rounded bg-white/5" /><div className="h-16 rounded bg-white/5" /></div></div><div className="mt-4 flex h-24 items-center justify-center rounded-xl bg-white/10"><LineChart size={40} className="text-white/20" /></div></div>; }
